# Generated by Django 6.0.3 on 2026-04-12 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmileitCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=300)),
                (
                    "verification_rule",
                    models.CharField(
                        choices=[
                            ("aromatic", "Aromatic"),
                            ("hbond_donor", "Hydrogen Bond Donor"),
                            ("hbond_acceptor", "Hydrogen Bond Acceptor"),
                            ("hydrophobic", "Hydrophobic"),
                            ("smarts", "SMARTS Pattern"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "verification_smarts",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smileit_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key", "-version"],
            },
        ),
        migrations.CreateModel(
            name="SmileitPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stable_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=140)),
                ("smarts", models.CharField(max_length=2000)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("toxicophore", "Toxicophore"),
                            ("privileged", "Privileged"),
                        ],
                        max_length=30,
                    ),
                ),
                ("caption", models.CharField(max_length=300)),
                (
                    "source_reference",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("provenance_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["pattern_type", "name", "-version"],
                "indexes": [
                    models.Index(
                        fields=["pattern_type", "is_active"],
                        name="smileit_smi_pattern_ac82b2_idx",
                    ),
                    models.Index(
                        fields=["stable_id", "is_latest"],
                        name="smileit_smi_stable__b7616f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stable_id", "version"),
                        name="unique_smileit_pattern_stable_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SmileitSubstituent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stable_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("smiles_input", models.CharField(max_length=2000)),
                ("smiles_canonical", models.CharField(db_index=True, max_length=2000)),
                ("anchor_atom_indices", models.JSONField(default=list)),
                (
                    "source_reference",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("provenance_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smileit_substituents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="SmileitSubstituentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_passed", models.BooleanField(default=True)),
                (
                    "verification_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substituent_links",
                        to="smileit.smileitcategory",
                    ),
                ),
                (
                    "substituent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_links",
                        to="smileit.smileitsubstituent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="smileitsubstituent",
            name="categories",
            field=models.ManyToManyField(
                related_name="substituents",
                through="smileit.SmileitSubstituentCategory",
                to="smileit.smileitcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="smileitcategory",
            index=models.Index(
                fields=["key", "is_latest"], name="smileit_smi_key_21b494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smileitcategory",
            index=models.Index(
                fields=["is_active"], name="smileit_smi_is_acti_d158a2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="smileitcategory",
            constraint=models.UniqueConstraint(
                fields=("key", "version"), name="unique_smileit_category_key_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="smileitcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("verification_rule", "smarts"),
                        models.Q(("verification_smarts", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("verification_rule", "smarts"), _negated=True),
                        ("verification_smarts", ""),
                    ),
                    _connector="OR",
                ),
                name="smileit_category_smarts_rule_consistency",
            ),
        ),
        migrations.AddIndex(
            model_name="smileitsubstituentcategory",
            index=models.Index(
                fields=["category", "substituent"],
                name="smileit_smi_categor_ed1cde_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="smileitsubstituentcategory",
            constraint=models.UniqueConstraint(
                fields=("substituent", "category"),
                name="unique_smileit_substituent_category",
            ),
        ),
        migrations.AddIndex(
            model_name="smileitsubstituent",
            index=models.Index(
                fields=["stable_id", "is_latest"], name="smileit_smi_stable__4c424c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smileitsubstituent",
            index=models.Index(
                fields=["is_active"], name="smileit_smi_is_acti_1329c4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="smileitsubstituent",
            constraint=models.UniqueConstraint(
                fields=("stable_id", "version"),
                name="unique_smileit_substituent_stable_version",
            ),
        ),
    ]
