# Generated by Django 6.0.3 on 2026-04-08 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smileit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="smileitcategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="smileit_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="smileitsubstituent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="smileit_substituents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="smileitcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("verification_rule", "smarts"),
                        models.Q(("verification_smarts", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("verification_rule", "smarts"), _negated=True),
                        ("verification_smarts", ""),
                    ),
                    _connector="OR",
                ),
                name="smileit_category_smarts_rule_consistency",
            ),
        ),
    ]
