# Generated by Django 6.0.4 on 2026-04-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smileit", "0002_smileit_seed_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="smileitpattern",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="smileit_patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
