# Generated by Django 6.0.3 on 2026-03-09 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_hash', models.CharField(db_index=True, help_text='Hash SHA-256 for caching', max_length=64)),
                ('plugin_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('cache_hit', models.BooleanField(default=False)),
                ('parameters', models.JSONField(default=dict)),
                ('results', models.JSONField(blank=True, default=dict, null=True)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
