# Generated by Django 6.0.3 on 2026-03-11 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_hash', models.CharField(max_length=64, unique=True)),
                ('plugin_name', models.CharField(max_length=100)),
                ('algorithm_version', models.CharField(max_length=50)),
                ('result_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScientificJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_hash', models.CharField(db_index=True, help_text='Hash SHA-256 for caching', max_length=64)),
                ('plugin_name', models.CharField(max_length=100)),
                ('algorithm_version', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('cache_hit', models.BooleanField(default=False)),
                ('cache_miss', models.BooleanField(default=True)),
                ('parameters', models.JSONField(default=dict)),
                ('results', models.JSONField(blank=True, default=dict, null=True)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Porcentaje de progreso entre 0 y 100.')),
                ('progress_stage', models.CharField(default='pending', help_text='Etapa actual de ejecución: pending/queued/running/caching/completed/failed.', max_length=40)),
                ('progress_message', models.CharField(default='Job creado y pendiente de ejecución.', help_text='Mensaje corto y legible del estado de progreso.', max_length=255)),
                ('progress_event_index', models.PositiveIntegerField(default=0, help_text='Contador incremental de eventos de progreso emitidos.')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Última señal de vida del proceso de ejecución del job.', null=True)),
                ('recovery_attempts', models.PositiveIntegerField(default=0, help_text='Cantidad de intentos de recuperación aplicados al job.')),
                ('max_recovery_attempts', models.PositiveIntegerField(default=5, help_text='Cantidad máxima de reencolados automáticos permitidos.')),
                ('last_recovered_at', models.DateTimeField(blank=True, help_text='Marca temporal del último intento de recuperación activa.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScientificJobLogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_index', models.PositiveIntegerField(help_text='Indice incremental de evento dentro del job.')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='Nivel del log emitido por runtime o plugin.', max_length=10)),
                ('source', models.CharField(default='core.runtime', help_text='Origen del evento de log para diagnostico.', max_length=80)),
                ('message', models.CharField(help_text='Mensaje de log legible para diagnostico de ejecucion.', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Contexto estructurado adicional del evento.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_events', to='core.scientificjob')),
            ],
            options={
                'ordering': ['event_index', 'created_at'],
                'indexes': [models.Index(fields=['job', 'event_index'], name='core_scient_job_id_aa0d63_idx'), models.Index(fields=['job', 'created_at'], name='core_scient_job_id_c02962_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'event_index'), name='unique_job_log_event_index')],
            },
        ),
    ]
