# Generated by Django 6.0.4 on 2026-05-25 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfRegistrationToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Código corto de 12 caracteres para compartir como invitación.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción contextual del token (ej: 'Invitación Lab Alpha Q1').",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Desactivar para revocar el token sin eliminarlo."),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1, help_text="Cantidad máxima de usos permitidos. 0 = ilimitado."
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Contador de registros exitosos usando este token."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, default=None, help_text="Fecha de expiración. None = nunca expira.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario root que generó el token.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_registration_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Grupo al que se asignará el usuario al registrarse.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_tokens",
                        to="core.workgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de auto-registro",
                "verbose_name_plural": "Tokens de auto-registro",
                "ordering": ["-created_at"],
            },
        ),
    ]
