# Generated by Django 6.0.3 on 2026-03-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificjob',
            name='progress_event_index',
            field=models.PositiveIntegerField(default=0, help_text='Contador incremental de eventos de progreso emitidos.'),
        ),
        migrations.AddField(
            model_name='scientificjob',
            name='progress_message',
            field=models.CharField(default='Job creado y pendiente de ejecución.', help_text='Mensaje corto y legible del estado de progreso.', max_length=255),
        ),
        migrations.AddField(
            model_name='scientificjob',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de progreso entre 0 y 100.'),
        ),
        migrations.AddField(
            model_name='scientificjob',
            name='progress_stage',
            field=models.CharField(default='pending', help_text='Etapa actual de ejecución: pending/queued/running/caching/completed/failed.', max_length=40),
        ),
    ]
