# Generated by Django 6.0.3 on 2026-03-12 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScientificJobInputArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("input", "Input"), ("auxiliary", "Auxiliary")],
                        default="input",
                        help_text="Rol del artefacto para trazabilidad de negocio.",
                        max_length=20,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Nombre del campo multipart de origen.",
                        max_length=80,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Nombre de archivo reportado por el cliente.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream",
                        help_text="Tipo MIME recibido durante la carga.",
                        max_length=120,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        help_text="Hash SHA-256 calculado sobre el contenido completo.",
                        max_length=64,
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Tamaño total del artefacto en bytes.",
                    ),
                ),
                (
                    "chunk_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de chunks persistidos para reconstrucción.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_artifacts",
                        to="core.scientificjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "field_name"],
                        name="core_scient_job_id_f5959c_idx",
                    ),
                    models.Index(
                        fields=["job", "created_at"],
                        name="core_scient_job_id_dc5e64_idx",
                    ),
                    models.Index(
                        fields=["sha256"], name="core_scient_sha256_734d1f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScientificJobInputArtifactChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="Índice incremental del chunk para reconstrucción ordenada.",
                    ),
                ),
                (
                    "chunk_data",
                    models.BinaryField(help_text="Contenido binario del fragmento."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.scientificjobinputartifact",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["artifact", "chunk_index"],
                        name="core_scient_artifac_a4993d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artifact", "chunk_index"),
                        name="unique_input_artifact_chunk_index",
                    )
                ],
            },
        ),
    ]
