# Generated by Django 6.0.3 on 2026-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_hash', models.CharField(max_length=64, unique=True)),
                ('plugin_name', models.CharField(max_length=100)),
                ('algorithm_version', models.CharField(max_length=50)),
                ('result_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='scientificjob',
            name='algorithm_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='scientificjob',
            name='cache_miss',
            field=models.BooleanField(default=True),
        ),
    ]
