# Generated by Django 6.0.3 on 2026-03-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scientificjobinputartifact",
            new_name="core_scient_expires_57f930_idx",
            old_name="core_artifac_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="scientificjobinputartifact",
            new_name="core_scient_chunks__0d32fb_idx",
            old_name="core_artifac_purged_idx",
        ),
        migrations.AlterField(
            model_name="scientificjob",
            name="job_hash",
            field=models.CharField(
                db_index=True, help_text="Hash SHA-256 for caching", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="scientificjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scientificjobinputartifact",
            name="chunks_purged_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Fecha en que se eliminaron los chunks binarios. None = chunks aún disponibles en DB.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scientificjobinputartifact",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Fecha de expiración de los chunks binarios. None = archivo pequeño, "
                + "se conserva de forma permanente. Pasada esta fecha la tarea de limpieza borra los chunks pero"
                + " preserva los metadatos y el resultado del job.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scientificjoblogevent",
            name="event_index",
            field=models.PositiveIntegerField(
                help_text="Indice incremental de evento dentro del job."
            ),
        ),
        migrations.AlterField(
            model_name="scientificjoblogevent",
            name="message",
            field=models.CharField(
                help_text="Mensaje de log legible para diagnostico de ejecucion.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="scientificjoblogevent",
            name="source",
            field=models.CharField(
                default="core.runtime",
                help_text="Origen del evento de log para diagnostico.",
                max_length=80,
            ),
        ),
    ]
