# Generated by Django 6.1.1 on 2026-09-23 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_self_registration_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scientificjob",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Expiración del job. Solo se define en jobs anónimos (sin owner) creados desde las rutas públicas; se purgan al vencer.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="scientificjob",
            index=models.Index(fields=["expires_at"], name="core_scient_expires_876cb8_idx"),
        ),
    ]
