# Generated by Django 6.0.3 on 2026-04-08 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_scientificjob_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="apppermission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", False), ("user__isnull", True)),
                    models.Q(("group__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="app_permission_exactly_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="apppermission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False), ("user__isnull", True)),
                fields=("group", "app_name"),
                name="unique_group_app_permission",
            ),
        ),
        migrations.AddConstraint(
            model_name="apppermission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", True), ("user__isnull", False)),
                fields=("user", "app_name"),
                name="unique_user_app_permission",
            ),
        ),
    ]
