# Generated by Django 6.0.3 on 2026-03-30 23:14

from django.db import migrations, models


def _backfill_null_error_trace_to_empty_string(
    apps: migrations.state.Apps,
    schema_editor: object,
) -> None:
    """Normaliza registros históricos: NULL -> cadena vacía en error_trace."""
    del schema_editor
    scientific_job_model = apps.get_model("core", "ScientificJob")
    scientific_job_model.objects.filter(error_trace__isnull=True).update(error_trace="")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_cancelled_status"),
    ]

    operations = [
        migrations.RunPython(
            _backfill_null_error_trace_to_empty_string,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="scientificjob",
            name="error_trace",
            field=models.TextField(blank=True, default=""),
        ),
    ]
