# Generated by Django 6.0.4 on 2026-04-15 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CadmaReferenceLibrary",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("disease_name", models.CharField(db_index=True, max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("paper_reference", models.CharField(blank=True, default="", max_length=300)),
                ("paper_url", models.CharField(blank=True, default="", max_length=500)),
                ("source_reference", models.CharField(blank=True, default="", max_length=80)),
                ("provenance_metadata", models.JSONField(blank=True, default=dict)),
                ("reference_rows", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cadma_reference_libraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cadma_reference_libraries",
                        to="core.workgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["disease_name", "name", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CadmaReferenceSourceFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("field_name", models.CharField(max_length=80)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("file", models.FileField(upload_to="cadma_py/reference_sources/%Y/%m/%d")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="cadma_py.cadmareferencelibrary",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "field_name", "original_filename"],
            },
        ),
        migrations.AddIndex(
            model_name="cadmareferencelibrary",
            index=models.Index(fields=["source_reference", "is_active"], name="cadma_py_ca_source__21c9b6_idx"),
        ),
        migrations.AddIndex(
            model_name="cadmareferencelibrary",
            index=models.Index(fields=["group", "is_active"], name="cadma_py_ca_group_i_1592d2_idx"),
        ),
        migrations.AddIndex(
            model_name="cadmareferencelibrary",
            index=models.Index(fields=["created_by", "is_active"], name="cadma_py_ca_created_9eccc7_idx"),
        ),
        migrations.AddIndex(
            model_name="cadmareferencesourcefile",
            index=models.Index(fields=["library", "field_name"], name="cadma_py_ca_library_d36f80_idx"),
        ),
    ]
